"""Helpers for matching 18xx.games server-side auto-action validation."""

from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

EXPECTED_AUTO_ACTIONS_PATH = Path(__file__).with_name("expected_auto_actions.rb")
_POST_METADATA_KEYS = {"created_at", "id", "user"}


def strip_post_action_metadata(action: dict) -> dict:
    """Remove fields generated by the 18xx server when an action is posted."""
    cleaned = {}
    for key, value in action.items():
        if key in _POST_METADATA_KEYS or value is None:
            continue
        if key == "auto_actions" and isinstance(value, list):
            cleaned[key] = [strip_post_action_metadata(item) for item in value]
        else:
            cleaned[key] = value
    return cleaned


def attach_expected_auto_actions(
    game_data: dict,
    action: dict,
    *,
    timeout: float = 30.0,
) -> dict:
    """Return ``action`` with the auto_actions 18xx will require on POST."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as game_file:
        json.dump(game_data, game_file)
        game_path = game_file.name

    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as action_file:
        json.dump(action, action_file)
        action_path = action_file.name

    try:
        result = subprocess.run(
            ["ruby", str(EXPECTED_AUTO_ACTIONS_PATH), game_path, action_path],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    finally:
        Path(game_path).unlink(missing_ok=True)
        Path(action_path).unlink(missing_ok=True)

    if result.returncode != 0:
        raise RuntimeError(
            "18xx auto-action simulation failed "
            f"(rc={result.returncode}): {result.stderr.strip()}"
        )

    simulated = json.loads(result.stdout)
    auto_actions = simulated.get("auto_actions") or []

    enriched = dict(action)
    if auto_actions:
        enriched["auto_actions"] = [
            strip_post_action_metadata(auto_action)
            for auto_action in auto_actions
        ]
    else:
        enriched.pop("auto_actions", None)
    return enriched
